apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-jenkins
  name: test-jenkins
  namespace: default
spec:
  ports:
    - name: http
      port: 9999
      protocol: TCP
      targetPort: 9999
      nodePort: 31999
  selector:
    app: test-jenkins
  sessionAffinity: None
  type: NodePort