# 使用变量的方式
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  {{- $realName := .Release.Name -}}
  {{- with .Values.favorite }}
  drink: {{ .drink | default "tea" | quote }}
  food: {{ .food | upper | quote }}
  release: {{ $realName }}
  {{- end }}

---

# for循环里面使用变量
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  {{- $realName := .Release.Name -}}
  {{- with .Values.favorite }}
  drink: {{ .drink | default "tea" | quote }}
  food: {{ .food | upper | quote }}
  release: {{ $realName }}
  {{- end }}
  toppings: |-
  {{- range $index, $topping := .Values.pizzaToppings }}
    {{ $index }}: {{ $topping }}
  {{- end }}

---

# for循环直接遍历key - value
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  {{- $realName := .Release.Name -}}
  {{- range $key, $value := .Values.favorite }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  toppings: |-
  {{- range $index, $topping := .Values.pizzaToppings }}
  {{ $index }}: {{ $topping }}
  {{- end }}
